### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by iamhealthy** [xielab2017/EasyMicroPlot#1]
> install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0')
Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
> install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0',upgrade = 'never')
Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
______________________________________________________
Above is the problem I encounted. Could you please figure out how to fix it?
Many thanks in advance! :-)

**Comment by liubingdong** [comment]
> > install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0')
> > Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
> > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
> > install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0',upgrade = 'never')
> > Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
> > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
> 
> Above is the problem I encounted. Could you please figure out how to fix it? Many thanks in advance! :-)


I can not reproduce this bug on my mac, and maybe it only  occur on windows system.
Here is a related issue below which may help you.
https://github.com/r-lib/remotes/issues/130
or 
https://www.cnblogs.com/jessepeng/p/14077003.html  (for Chinese mainland users)

**Comment by iamhealthy** [comment]
> > > install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0')
> > > Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
> > > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > > cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
> > > install_github("xielab2017/EasyMicroPlot",subdir='Version_0.5.0',upgrade = 'never')
> > > Downloading GitHub repo xielab2017/EasyMicroPlot@HEAD
> > > Error in utils::download.file(url, path, method = method, quiet = quiet,  :
> > > cannot open URL 'https://api.github.com/repos/xielab2017/EasyMicroPlot/tarball/HEAD'
> > 
> > 
> > Above is the problem I encounted. Could you please figure out how to fix it? Many thanks in advance! :-)
> 
> I can not reproduce this bug on my mac, and maybe it only occur on windows system. Here is a related issue below which may help you. [r-lib/remotes#130](https://github.com/r-lib/remotes/issues/130) or https://www.cnblogs.com/jessepeng/p/14077003.html (for Chinese mainland users)

Your tip does work. Thanks!

**Comment by iamhealthy** [comment]
Hi, how to understand the letters of "a" and "b" of Figure 2D and 2E (PMID: 35058973. The cognate paper of the R package). I guess they mean some kind of statistical significance. Could you please clarify? Thanks!

**Comment by xielab2017** [comment]
Yes, you are right it is statistic significance&nbsp;


-----------------------------------

 

 
Hi, how to understand the letters of "a" and "b" of Figure 2D and 2E (PMID: 35058973. The cognate paper of the R package). I guess they mean some kind of statistical significance. Could you please clarify? Thanks!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iamhealthy** [comment]
Hi Liubingdong, could you clarify how to understand "evcent_value", "betweenness_value", "page_rank_value", "transitivity", "centralization_degree", "graph_density", which are all related to co-occurrence analysis? Or Could you share me some online resource, from where we amateurs could have a deep understanding on those values. Thanks!

**Comment by liubingdong** [comment]
> Hi Liubingdong, could you clarify how to understand "evcent_value", "betweenness_value", "page_rank_value", "transitivity", "centralization_degree", "graph_density", which are all related to co-occurrence analysis? Or Could you share me some online resource, from where we amateurs could have a deep understanding on those values. Thanks!

Yes, all these value are  related to co-occurrence analysis, which could be utilized to assess network. EMP package calculates this result by package 'igraph', so you could get more detailed information in its help document .(https://igraph.org/r/html/latest/)

**Comment by iamhealthy** [comment]
Hi Liubingdong, via 'RFCV' function, union and intersect signature could be generated. I wonder which signature (even beyond the union and intersect signatures) could be finally treated as optimum clinical auxiliary signature?
So sorry for so many questions, and really appreciate your patient answer.

**Comment by iamhealthy** [comment]
:-)

**Comment by liubingdong** [comment]
> Hi Liubingdong, via 'RFCV' function, union and intersect signature could be generated. I wonder which signature (even beyond the union and intersect signatures) could be finally treated as optimum clinical auxiliary signature? So sorry for so many questions, and really appreciate your patient answer.



It is hard to make a simple explanation. First, it is well known that random forest model will generate different results at different random seed.  RFCV function in EMP is a easy way to preform N-fold cross validation and combine these results at different seeds, and select the optimum feature number according to the lowest mean error rate and standard deviation in curve plot (for example the number is 6).  But, the top 6 taxa is not same in these results, so EMP provides a union and intersect of taxa sets for users.  More demo examples and information could be found in papers below:
https://pubmed.ncbi.nlm.nih.gov/34523948/
https://pubmed.ncbi.nlm.nih.gov/34950610/
https://pubmed.ncbi.nlm.nih.gov/31912587/
https://pubmed.ncbi.nlm.nih.gov/31456757/

I hope this may help u.
