### ISSUE TITLE
Something is wrong: 选择了未定义的列

### ISSUE THREAD

**Issue by iamhealthy** [xielab2017/EasyMicroPlot#2]
Hi Liubingdong,

When running 'EMP_MICRO(micro,mapping)', there is an alert emerging as "Something is wring : 选择了未定义的列".
The object 'micro' is as the attached file "micro.csv"; the object 'mapping' is as the attached "mapping.csv".

Could you please reproduce it, and see if there is something wrong?

Thanks :-)
[micro.csv](https://github.com/xielab2017/EasyMicroPlot/files/8066847/micro.csv)
[mapping.csv](https://github.com/xielab2017/EasyMicroPlot/files/8066868/mapping.csv)

**Comment by iamhealthy** [comment]
The columns of micro.csv (except column 1, which is "ID") and mapping$SampleID are totally matched. :-)

**Comment by iamhealthy** [comment]
:-）

**Comment by liubingdong** [comment]
> Hi Liubingdong,
> 
> When running 'EMP_MICRO(micro,mapping)', there is an alert emerging as "Something is wring : 选择了未定义的列". The object 'micro' is as the attached file "micro.csv"; the object 'mapping' is as the attached "mapping.csv".
> 
> Could you please reproduce it, and see if there is something wrong?
> 
> Thanks :-) [micro.csv](https://github.com/xielab2017/EasyMicroPlot/files/8066847/micro.csv) [mapping.csv](https://github.com/xielab2017/EasyMicroPlot/files/8066868/mapping.csv)

I  found many NA in your micro.csv for example (MDL001.NC.DNA.6.DNA.A46.20200413,  MDL001.PC.RNA.A40.20200413,  MDL001.2C2016010T.DNA.A43.20200413). You need delete these samples in micro.csv and mapping.csv. After deleting these samples, the workflow worked well. Hope this could help you and sorry for my late answer.
