### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by emihoe** [xielab2017/EasyMicroPlot#3]
Hi,
Can you please provide more information on how users data should be imported for EasyMicroPlot to use.
I have currently just imported a csv file for my metadata and a csv file for the read counts of each taxa/samples
Thank you,
Emily

**Comment by liubingdong** [comment]
> Hi, Can you please provide more information on how users data should be imported for EasyMicroPlot to use. I have currently just imported a csv file for my metadata and a csv file for the read counts of each taxa/samples Thank you, Emily

Sorry to answer it late.   EMP package provide users a demo data for practice.  After library(EasyMicroPlot), you could data(EMP) to check the format of data. I hope this could help you. If any more questions or bugs, please let me know. Thank you.
